name: Elixir Template CI
# This workflow runs only when called by another workflow
on:
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string
        description: "The directory of the app to test (e.g., apps/farm)"
env:
  MIX_ENV: test
jobs:
  quality-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -eo pipefail {0}
    steps:
      - uses: actions/checkout@v6
      # Setup Mise (caches dependencies automatically)
      - uses: jdx/mise-action@v3
      # Run Lint (using the path passed in the input)
      - name: Setup Hex
        run: mix local.hex --force && mix local.rebar --force
      - name: Get Dependencies
        run: mix deps.get
        working-directory: ${{ inputs.app_dir }}
      - name: Compile
        run: mix compile --warning-as-errors --force
      - name: Lint
        working-directory: ${{ inputs.app_dir }}
        run: mix credo --strict --format=json
      # Run Tests
      - name: Test
        working-directory: ${{ inputs.app_dir }}
        run: mix test
